pipeline:
    name: testpip
    identifier: testpip
    projectIdentifier: testphpproje
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: gitrepoconnector
                build: <+input>
    stages:
        - stage:
              name: buildstsg
              identifier: buildstsg
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: kscls
                          namespace: harness-delegate-ng
                          automountServiceAccountToken: true
                          nodeSelector: {}
                          harnessImageConnectorRef: testimage
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: testshell
                                identifier: testshell
                                spec:
                                    connectorRef: testimage
                                    image: ubantu:latest
                                    shell: Sh
                                    command: echo "hello"
